mash-up-kr/ssam-d-Android

- app/build.gradle
- build.gradle
- buildSrc/build.gradle.kts
- buildSrc/src/main/java/dependencies/Dep.kt
- buildSrc/src/main/java/dependencies/Modules.kt
- buildSrc/src/main/java/dependencies/Versions.kt
- data/build.gradle
- domain/build.gradle
- presentation/build.gradle
- kotlin DSL 적용해 build.gradle을 관리합니다.
close #6
> #6 kotlin DSL 적용해 build.gradle 관리하기

- presentation/src/main/java/com/mashup/presentation/ui/common/KeyLinkButton.kt
- presentation/src/main/java/com/mashup/presentation/ui/theme/Color.kt
- presentation/src/main/java/com/mashup/presentation/ui/theme/Theme.kt
- color 재정의
- 디자인 컴포넌트 기반으로 공통버튼 만듦
- height는 55, 44 두개 사용
- text는 필수값
close #<10>
> #10 공통버튼 제작

- presentation/src/main/java/com/mashup/presentation/ui/common/KeyLinkMintText.kt
- presentation/src/main/java/com/mashup/presentation/ui/common/KeyLinkText.kt
- 디자인 컴포넌트 기반 공통 text 구현
- text 필수
close #12
> #12 keylink 공통 text 구현

- presentation/src/main/res/values-night/themes.xml
- presentation/src/main/res/values-v26/typography.xml
- presentation/src/main/res/values-v28/typography.xml
- presentation/src/main/res/values/colors.xml
- presentation/src/main/res/values/themes.xml
- presentation/src/main/res/values/typography.xml
- color 추가
- typography 추가
- api 버전 별 분기
| typography 샘플 | <img src="https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/4fe20d1d-dedc-44e6-8a0b-3cef5e889a0e" width=400 /> |
close #20
> #20 xml 리소스 정의

- app/src/main/AndroidManifest.xml
- presentation/src/main/java/com/mashup/presentation/common/widget/KeyLinkLogoutDialog.kt
- presentation/src/main/java/com/mashup/presentation/common/widget/KeyLinkToolbar.kt
- presentation/src/main/java/com/mashup/presentation/mypage/PrivacyPolicyFragment.kt
- presentation/src/main/java/com/mashup/presentation/mypage/TermsOfServiceFragment.kt
- presentation/src/main/java/com/mashup/presentation/mypage/profile/ProfileFragment.kt
- presentation/src/main/res/layout/fragment_privacy_policy.xml
- presentation/src/main/res/layout/fragment_profile.xml
- presentation/src/main/res/layout/fragment_terms_of_service.xml
- presentation/src/main/res/layout/item_profile_user_info.xml
- presentation/src/main/res/values/strings.xml
- 마이페이지 디테일 작업
- 닉네임 수정 버튼 삭제
- 이용약관, 개인정보 처리방침 웹뷰 연결
- 로그아웃 다이얼로그 연결
- 웹뷰에 연결할 URL은 임시로 naver로 연결했슴다
| 프로필 | <img src="https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/dd694430-9269-47b7-bee4-670d4c77f5ef" width=300/> |
close #37
> 마이페이지 디테일 작업

- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/mashup/presentation/mypage/profile/Options.kt
- presentation/src/main/java/com/mashup/presentation/mypage/profile/ProfileItemDecoration.kt
- presentation/src/main/java/com/mashup/presentation/mypage/profile/ProfileViewType.kt
- presentation/src/main/res/layout/item_profile_navigation_content.xml
- presentation/src/main/res/navigation/graph_profile.xml
- presentation/src/main/res/values-v26/typography.xml
- presentation/src/main/res/values-v28/typography.xml
- presentation/src/main/res/values/strings.xml
- presentation/src/main/res/values/typography.xml
- 보낸 시그널 아이템 추가
- ItemDecoration에 들어가는 margin값은 의도된거라고 전달받아서 그대로 추가했습니당
| 보낸 시그널 아이템 추가 | <img src="https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/ba24e398-009a-41ae-ba43-b173871302f1" width=300 /> |
close #45
> 마이페이지 보낸 시그널 추가

- presentation/src/main/java/com/mashup/presentation/onboarding/OnBoardingScreen.kt
- presentation/src/main/res/values/strings.xml
- 온보딩 화면 string resource 정리
- 온보딩 화면 string resource 정리했슈
- 닉넴쪽은 안건들였슴다
| _ | _ |
close #72
> #72 온보딩 화면 string resource 정리

- presentation/src/main/java/com/mashup/presentation/home/HomeScreen.kt
- Typo 잘못설정한것, 디자인변경으로 인한 컴포넌트 삭제 
- Typo 잘못설정한것, 디자인변경으로 인한 컴포넌트 삭제 헤헷 빌드돌리니까 왕창큰 폰트나와서 깜짝놀람
- 올리면서 없어진 컴포넌트 살짝 삭제해서 올림
| Typo 잘못설정한것  | none |
close #75
> [feat] #84 typo 재설정 및 디자인 변경으로 컴포넌트 삭제

- presentation/src/main/java/com/mashup/presentation/home/HomeScreen.kt
- presentation/src/main/java/com/mashup/presentation/ui/common/KeyLinkSnackBar.kt
- presentation/src/main/java/com/mashup/presentation/ui/theme/Color.kt
- presentation/src/main/res/drawable/ic_square_check_mint_24.xml
- presentation/src/main/res/values/strings.xml
- 커스텀 스낵바 생성했습니다.
- 사용을 위해서는 Scaffold에서 `scaffoldState.snacbarHostState`로 접근해야 합니당 (링크 참고하시길~)
- https://programmmingphil.tistory.com/30
- none
| KeyLinkSnackBar 생성 | <img src="https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/9590950a-0732-40d3-a84b-153714a396de" width=600 /> |
close #86
> #86 KeyLinkSnackBar 정의

- presentation/src/main/java/com/mashup/presentation/home/HomeScreen.kt
- presentation/src/main/res/drawable/ic_tag_mint.xml
- 홈 스크롤 시 애니메이션
- 애니메이션 폴리싱 작업은 api 이후에 할게요~
- 근데 왜 나는 화면이 안나오고 링크로만나오는거얌?
| 홈 스크롤 |https://github.com/mash-up-kr/ssam-d-Android/assets/37477660/6e2b9c68-e6a1-46cc-ab14-6388f83299fc|
close #98
> 홈 스크롤 시 애니메이션

- presentation/src/main/java/com/mashup/presentation/common/extension/LazyGridState.kt
- presentation/src/main/java/com/mashup/presentation/common/extension/LazyListState.kt
- presentation/src/main/java/com/mashup/presentation/feature/chat/navigation/ChatNavigation.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/chat/compose/Chat.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/chat/compose/ChatDetailScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/chat/compose/MatchedKeywords.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/chat/compose/OtherUserInfo.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/chat/model/ChatDetailUiModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/home/HomeScreen.kt
- presentation/src/main/java/com/mashup/presentation/ui/common/KeyLinkChip.kt
- presentation/src/main/java/com/mashup/presentation/ui/theme/Typography.kt
- 이 [PR](https://github.com/mash-up-kr/ssam-d-Android/pull/126)이 깃이 살짝 꼬여서 깔끔하게 올릴라고 체리픽했심다.
- none
| 핑퐁 |기존 PR 확인부탁스 |
close #125
> 채팅 핑퐁화면 디자인 변경

- presentation/src/main/java/com/mashup/presentation/feature/onboarding/OnBoardingFragment.kt
- presentation/src/main/java/com/mashup/presentation/feature/onboarding/OnBoardingScreen.kt
- presentation/src/main/java/com/mashup/presentation/ui/common/KeyLinkLoading.kt
- presentation/src/main/res/values/strings.xml
- 온보딩 뒤로가기 다이얼로그
- scaffold로 수정
- Route 상위 컴포저블 생성
- string 잘못들어간거수정
- 재성아 다이얼로그 때잉큐~
- 로그인으로 돌아가는건 네비게이션하고 하겠읍니다.
| 뒤로가기 다이얼로그 |https://github.com/mash-up-kr/ssam-d-Android/assets/37477660/9f309a2f-e493-417b-9a58-607166e13508|
https://github.com/mash-up-kr/ssam-d-Android/assets/37477660/9f309a2f-e493-417b-9a58-607166e13508
close #116
> 온보딩 뒤로가기 다이얼로그

- buildSrc/src/main/java/dependencies/Dep.kt
- data/build.gradle
- domain/build.gradle
- presentation/build.gradle
- presentation/src/main/AndroidManifest.xml
- presentation/src/main/java/com/mashup/presentation/feature/chat/compose/ChatScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/chat/navigation/ChatNavigation.kt
- presentation/src/main/java/com/mashup/presentation/navigation/KeyLinkNavHost.kt
- 채팅 비어있을 때 시그널 보내기 연결
- 이 PR에 Paging3 의존성 추가가 포함되어있습니다~
| 시그널 보내기 연결 | <img src="https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/4a67b977-b7af-4fbb-8e63-6d833c87b19c" width=300 /> |
close #163
> #163 채팅 비어있을 때 시그널 보내기 연결

- presentation/src/main/java/com/mashup/presentation/KeyLinkApp.kt
- presentation/src/main/java/com/mashup/presentation/KeyLinkAppState.kt
- presentation/src/main/java/com/mashup/presentation/feature/chat/navigation/ChatNavigation.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/message/compose/MessageDetailScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/home/navigation/HomeNavigation.kt
- presentation/src/main/java/com/mashup/presentation/feature/reply/ReplyScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/reply/navigation/ReplyNavigation.kt
- presentation/src/main/java/com/mashup/presentation/feature/report/ReportScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/subscribe/SubscribeKeywordScreen.kt
- presentation/src/main/java/com/mashup/presentation/navigation/KeyLinkNavHost.kt
- presentation/src/main/java/com/mashup/presentation/navigation/KeyLinkNavigationRoute.kt
- presentation/src/main/java/com/mashup/presentation/navigation/RouteConst.kt
- presentation/src/main/java/com/mashup/presentation/ui/common/KeyLinkSnackBar.kt
- presentation/src/main/res/values/strings.xml
- 키워드 저장 시 스낵바 표시
- 답장 완료 시 스낵바 표시
- 신고 접수 시 스낵바 표시
- none
| 키워드 저장 | <img src = "https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/01a869fc-a456-423c-99c0-6040d16bc62b" width = 300 /> |
| 답장 완료 | <img src = "https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/e15dc7a9-d57f-48f6-a8b0-d30d3011cc4b" width = 300 /> |
| 신고 접수 | <img src = "https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/b459d3e2-6c5a-4df5-b312-ed7239f070af" width = 300 /> |
close #152
> #152 화면 별 스낵바 표시

- data/src/main/java/com/mashup/data/di/RepositoryModule.kt
- data/src/main/java/com/mashup/data/di/ServiceModule.kt
- data/src/main/java/com/mashup/data/repository/ChatRepositoryImpl.kt
- data/src/main/java/com/mashup/data/source/remote/datasource/RemoteChatDataSource.kt
- data/src/main/java/com/mashup/data/source/remote/dto/responsebody/chat/ChatDetailResponse.kt
- data/src/main/java/com/mashup/data/source/remote/service/ChatService.kt
- domain/src/main/java/com/mashup/domain/model/chat/ChatDetail.kt
- domain/src/main/java/com/mashup/domain/repository/ChatRepository.kt
- domain/src/main/java/com/mashup/domain/usecase/chat/GetChatDetailUseCase.kt
- #147 채팅상세 api data, domain layer
- none
close #147
> #147 채팅상세 api data, domain layer

- data/src/main/java/com/mashup/data/repository/UserRepositoryImpl.kt
- data/src/main/java/com/mashup/data/source/remote/datasource/RemoteUserDataSource.kt
- data/src/main/java/com/mashup/data/source/remote/dto/requestbody/AlarmRequestBody.kt
- data/src/main/java/com/mashup/data/source/remote/service/UserService.kt
- domain/src/main/java/com/mashup/domain/repository/UserRepository.kt
- domain/src/main/java/com/mashup/domain/usecase/mypage/DeleteUserUseCase.kt
- domain/src/main/java/com/mashup/domain/usecase/mypage/GetUserInformationUseCase.kt
- domain/src/main/java/com/mashup/domain/usecase/mypage/SaveAlarmStateUseCase.kt
- presentation/src/main/java/com/mashup/presentation/feature/onboarding/NotificationPermissionGuideFragment.kt
- presentation/src/main/java/com/mashup/presentation/feature/onboarding/NotificationPermissionScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/onboarding/NotificationPermissionViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/ProfileOptionsProvider.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/ProfileViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/ProfileViewType.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/compose/ProfileScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/compose/ProfileViewTypeContent.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/model/ProfileUiModel.kt
- 마이페이지 화면 api 연결 뚝딱쓰
- none
close #142 
close #162
> 마이페이지 화면 api 연결

- data/src/main/java/com/mashup/data/repository/ChatRepositoryImpl.kt
- data/src/main/java/com/mashup/data/repository/SignalRepositoryImpl.kt
- data/src/main/java/com/mashup/data/source/remote/dto/responsebody/chat/ChatRoomPagingResponse.kt
- data/src/main/java/com/mashup/data/source/remote/dto/responsebody/signal/ReceivedSignalResponse.kt
- data/src/main/java/com/mashup/data/source/remote/service/ChatService.kt
- data/src/main/java/com/mashup/data/source/remote/service/SignalService.kt
- data/src/main/java/com/mashup/data/source/remote/source/datasource/RemoteChatDataSource.kt
- data/src/main/java/com/mashup/data/source/remote/source/datasource/RemoteSignalDataSource.kt
- data/src/main/java/com/mashup/data/source/remote/source/paging/KeyLinkPagingSource.kt
- data/src/main/java/com/mashup/data/util/Paging.kt
- domain/src/main/java/com/mashup/domain/base/paging/PagedData.kt
- domain/src/main/java/com/mashup/domain/base/paging/Paging.kt
- domain/src/main/java/com/mashup/domain/model/chat/Room.kt
- domain/src/main/java/com/mashup/domain/repository/ChatRepository.kt
- domain/src/main/java/com/mashup/domain/usecase/chat/GetChatRoomsUseCase.kt
- presentation/src/main/java/com/mashup/presentation/feature/chat/model/RoomUiModel.kt
- 채팅방 조회 페이징 data, domain layer
- none
#146
> 채팅방 조회 페이징 data, domain layer

- data/src/main/java/com/mashup/data/source/remote/dto/responsebody/chat/ChatRoomPagingResponse.kt
- presentation/src/main/java/com/mashup/presentation/feature/chat/ChatViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/chat/compose/ChatListScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/chat/compose/ChatScreen.kt
- 채팅방 리스트 조회 페이징 presentation 연결
- none
| 채팅방리스트|![KakaoTalk_Photo_2023-07-19-17-47-45](https://github.com/mash-up-kr/ssam-d-Android/assets/37477660/ca0d9896-f394-4f4a-8fa2-8fa77b98b5f8)|
close #146
> 채팅방 리스트 조회 페이징 presentation 연결

- data/src/main/java/com/mashup/data/source/remote/dto/responsebody/chat/ChatRoomPagingResponse.kt
- domain/src/main/java/com/mashup/domain/model/chat/Room.kt
- presentation/src/main/java/com/mashup/presentation/feature/chat/compose/ChatListScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/chat/model/RoomUiModel.kt
-  api 추가된 응답값 반영
- none
close #<issue_number>
> [feat] #146 api 추가된 응답값 반영

- data/src/main/java/com/mashup/data/repository/ChatRepositoryImpl.kt
- data/src/main/java/com/mashup/data/source/remote/service/ChatService.kt
- data/src/main/java/com/mashup/data/source/remote/source/datasource/RemoteChatDataSource.kt
- domain/src/main/java/com/mashup/domain/repository/ChatRepository.kt
- domain/src/main/java/com/mashup/domain/usecase/chat/DisconnectRoomUseCase.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/ChatDetailViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/chat/compose/ChatDetailScreen.kt
- #187 시그널 끊기 api 연결
- none
| 시그널ㄲ끊기 | Sample |
https://github.com/mash-up-kr/ssam-d-Android/assets/37477660/0d380161-96a2-471c-b826-86d390415f84
close #187
> #187 시그널 끊기 api 연결

- data/src/main/java/com/mashup/data/repository/KeywordRepositoryImpl.kt
- data/src/main/java/com/mashup/data/source/remote/service/KeywordService.kt
- data/src/main/java/com/mashup/data/source/remote/source/datasource/RemoteKeywordDataSource.kt
- data/src/main/java/com/mashup/data/util/Paging.kt
- domain/src/main/java/com/mashup/domain/repository/KeywordRepository.kt
- domain/src/main/java/com/mashup/domain/usecase/GetSubscribeKeywordsUseCase.kt
- domain/src/main/java/com/mashup/domain/usecase/UpdateSubscribeKeywordsUseCase.kt
- presentation/src/main/java/com/mashup/presentation/feature/home/HomeViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/home/navigation/HomeNavigation.kt
- presentation/src/main/java/com/mashup/presentation/feature/subscribe/SubscribeKeywordScreen.kt
- 구독 키워드 저장 API 연결
- none
| 구독 키워드 저장 | <img src="https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/9845a316-e7c3-4f19-a813-6c42b30bf8e4" width=300 /> |
close #186
> #186 구독 키워드 저장 API 연결

- data/src/main/java/com/mashup/data/repository/SignalRepositoryImpl.kt
- data/src/main/java/com/mashup/data/source/remote/dto/responsebody/signal/ReceivedSignalResponse.kt
- data/src/main/java/com/mashup/data/source/remote/service/SignalService.kt
- data/src/main/java/com/mashup/data/source/remote/source/datasource/RemoteSignalDataSource.kt
- domain/src/main/java/com/mashup/domain/model/ReceivedSignal.kt
- domain/src/main/java/com/mashup/domain/model/Signal.kt
- domain/src/main/java/com/mashup/domain/repository/SignalRepository.kt
- domain/src/main/java/com/mashup/domain/usecase/GetReceivedSignalDetailUseCase.kt
- domain/src/main/java/com/mashup/domain/usecase/GetReceivedSignalUseCase.kt
- presentation/src/main/java/com/mashup/presentation/feature/home/model/SignalUiModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/navigation/ProfileNavigation.kt
- presentation/src/main/java/com/mashup/presentation/navigation/KeyLinkNavigationRoute.kt
- presentation/src/main/java/com/mashup/presentation/navigation/RouteConst.kt
- 받은 시그널 상세 조회 Domain 연결
- none
close #189
> #189 받은 시그널 상세 조회 Domain 연결

- presentation/src/main/java/com/mashup/presentation/feature/chat/compose/ChatListScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/chat/compose/ChatScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/home/HomeScreen.kt
- presentation/src/main/res/values/strings.xml
- pull To refresh
- 홈, 채팅방리스트만 우선 ㅇㅇ
- 채팅상세는 수진 작업 이후 붙일게요
close #190 #202
> pull To refresh

- data/src/main/java/com/mashup/data/source/remote/service/SignalService.kt
- presentation/src/main/java/com/mashup/presentation/common/extension/Long.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/message/model/MessageDetailUiModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/message/navigation/MessageDetailNavigation.kt
- presentation/src/main/java/com/mashup/presentation/feature/home/model/SignalUiModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/signal/received/ReceivedSignalDetailRoute.kt
- presentation/src/main/java/com/mashup/presentation/feature/signal/received/ReceivedSignalViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/signal/received/model/ReceivedSignalDetailUiModel.kt
- presentation/src/main/java/com/mashup/presentation/navigation/KeyLinkNavHost.kt
- 받은 시그널 상세 Presentation 연결
- none
| 받은 시그널 상세 | <img src="https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/e9109842-70cb-4263-ba38-58bee57f5948" width=300 /> |
close #199
> #199 받은 시그널 상세 Presentation 연결

- data/src/main/java/com/mashup/data/repository/OnboardingRepositoryImpl.kt
- data/src/main/java/com/mashup/data/repository/UserRepositoryImpl.kt
- data/src/main/java/com/mashup/data/source/local/datasource/LocalUserDataSource.kt
- domain/src/main/java/com/mashup/domain/repository/OnboardingRepository.kt
- domain/src/main/java/com/mashup/domain/repository/UserRepository.kt
- domain/src/main/java/com/mashup/domain/usecase/PatchNicknameUseCase.kt
- domain/src/main/java/com/mashup/domain/usecase/SaveOnboardingKeywordsUseCase.kt
> #151 닉네임+온보딩 키워드 저장

- presentation/src/main/java/com/mashup/presentation/feature/chat/compose/ChatScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/chat/compose/ChatDetailScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/home/HomeScreen.kt
- 채팅 디테일 pull-to-refresh
- none
| 로딩중 |https://github.com/mash-up-kr/ssam-d-Android/assets/37477660/dbd9bed4-6d57-420f-afe7-d4a24c8a3f9b|
| 리프레시 완 |https://github.com/mash-up-kr/ssam-d-Android/assets/37477660/68e854ae-ea71-4634-95bd-dd3531e95bb9|
close #211
> 채팅 디테일 pull-to-refresh

- data/src/main/java/com/mashup/data/source/local/datasource/LocalUserDataSource.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/ChatDetailViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/message/compose/MatchedKeywordContainer.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/message/compose/MessageDetailContainer.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/message/compose/MessageDetailScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/login/LoginActivity.kt
- presentation/src/main/java/com/mashup/presentation/feature/login/LoginViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/signal/received/ReceivedSignalDetailRoute.kt
- 메세지 / 시그널 상세 디자인 수정 사항 적용
|상세 |👇 |
https://github.com/mash-up-kr/ssam-d-Android/assets/51108983/677100b3-26b4-4e4b-b584-ff3d838d19a0
close #233
> #233 메세지 / 시그널 상세 디자인 수정 사항 적용

- presentation/src/main/java/com/mashup/presentation/feature/detail/chat/compose/ChatDetailScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/home/HomeViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/login/LoginActivity.kt
- presentation/src/main/java/com/mashup/presentation/feature/signal/send/SignalViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/signal/send/compose/SignalContentScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/signal/send/compose/SignalKeywordScreen.kt
- presentation/src/main/java/com/mashup/presentation/ui/common/BottomSheetSample.kt
- presentation/src/main/java/com/mashup/presentation/ui/common/KeyLinkBottomSheet.kt
- 버텀시트 레이아웃 깨짐
- none
| 버텀싵 레이아웃 |![KakaoTalk_Photo_2023-07-23-22-20-54](https://github.com/mash-up-kr/ssam-d-Android/assets/37477660/79c7de40-c652-4965-a196-d18ade381251)|
close #240 
close #241
> 버텀시트 레이아웃 깨짐

- buildSrc/src/main/java/dependencies/Dep.kt
- data/src/main/java/com/mashup/data/repository/UserRepositoryImpl.kt
- domain/src/main/java/com/mashup/domain/repository/UserRepository.kt
- domain/src/main/java/com/mashup/domain/usecase/mypage/LogoutUseCase.kt
- presentation/build.gradle
- presentation/src/main/java/com/mashup/presentation/feature/onboarding/OnBoardingScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/ProfileOptionsProvider.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/ProfileViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/compose/ProfileScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/compose/ProfileViewTypeContent.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/navigation/ProfileNavigation.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/policy/PrivacyPolicyScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/tos/TermsOfServiceScreen.kt
- presentation/src/main/java/com/mashup/presentation/ui/common/accompanist/KeyLinkWebView.kt
- #231 
- #238 
- 웹뷰는 현재 tistory를 띄우고 있지만 2차 배포에서는 html로 정적페이지 만들어서 올릴 예정입니다.
- 1차 배포에 포함되지 않는 기능들을 제외합니다.
| 1차 배포 프로필 화면 | <img src="https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/a7206008-33db-4f24-89db-ae0103487ea0" width=300 /> |
| 개인정보 처리방침 웹뷰 | <img src="https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/ce5b4ca5-d07c-44a9-9912-de91a7d5bf70" width=300 /> |
| 서비스 이용약관 웹뷰 | <img src="https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/a45ef613-91ab-46bf-8e5c-91806caba559" width=300 /> |
close #231 close #238
> #231 #238 프로필 웹뷰 적용 및 1차 배포에 포함되지 않는 기능 제외

- presentation/src/main/java/com/mashup/presentation/common/extension/Long.kt
- presentation/src/main/java/com/mashup/presentation/feature/chat/model/RoomUiModel.kt
- 하루까진 시간단위, 하루 지나면 날짜로 파싱
- none
close #<issue_number>
> 채팅방리스트 시간 파싱 변경

- .github/workflows/android.yml
- .gitignore
- app/build.gradle
- app/proguard-rules.pro
- data/src/debug/java/com/mashup/data/network/Const.kt
- data/src/main/java/com/mashup/data/di/NetworkModule.kt
- data/src/release/java/com/mashup/data/network/Const.kt
- 1차 배포
- 실서버 URL 적용
- CI 스크립트 수정
- keystore로 릴리즈모드 빌드하는건 CD에서 assembleRelease로 해야할 것 같습니당
- CI에서는 assembleDebug만 하는걸로 수정했습니당
close #217
> #217 1차 배포

- data/src/main/java/com/mashup/data/source/remote/dto/responsebody/UserResponseBody.kt
- domain/src/main/java/com/mashup/domain/model/User.kt
- presentation/src/main/java/com/mashup/presentation/feature/login/LoginActivity.kt
- presentation/src/main/java/com/mashup/presentation/feature/login/LoginViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/ProfileViewType.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/compose/ProfileViewTypeContent.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/model/ProfileUiModel.kt
- 닉네임 화면에서 앱 나갔다 들어오면 로그인 완료 화면으로 넘어감 이슈 수정
- 마이페이지 email 빈 값 허용 처리 필요
- none
| 닉네임 화면 이슈 | 
https://github.com/mash-up-kr/ssam-d-Android/assets/51108983/23725533-4ed3-489c-b949-3336b374f819
close #251 
close #252
> #251 #252 1차 배포 이슈 수정

- presentation/src/main/res/values/strings.xml
> #268 UI 텍스트 수정

- data/src/main/java/com/mashup/data/repository/UserRepositoryImpl.kt
- data/src/main/java/com/mashup/data/source/local/datasource/LocalUserDataSource.kt
- data/src/main/java/com/mashup/data/source/remote/source/datasource/RemoteUserDataSource.kt
- domain/src/main/java/com/mashup/domain/repository/UserRepository.kt
- domain/src/main/java/com/mashup/domain/usecase/mypage/WithdrawalUseCase.kt
- presentation/src/main/java/com/mashup/presentation/feature/login/LoginActivity.kt
- presentation/src/main/java/com/mashup/presentation/feature/login/LoginViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/onboarding/OnBoardingScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/ProfileOptionsProvider.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/ProfileViewType.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/compose/ProfileScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/compose/ProfileViewTypeContent.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/navigation/ProfileNavigation.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/withdrawal/WithdrawalScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/profile/withdrawal/WithdrawalViewModel.kt
- presentation/src/main/java/com/mashup/presentation/navigation/KeyLinkNavHost.kt
- presentation/src/main/java/com/mashup/presentation/navigation/KeyLinkNavigationRoute.kt
- presentation/src/main/java/com/mashup/presentation/navigation/RouteConst.kt
- presentation/src/main/res/values/strings.xml
- #258 
- 회원 탈퇴 기능 및 마이페이지 미적용 기능 제거
- none
| 변경된 마이페이지 | <img src="https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/05af1381-4f2d-45ad-8049-eb9a17deb519" width=300 /> |
| 회원 탈퇴 UI | <img src="https://github.com/mash-up-kr/ssam-d-Android/assets/51078673/c19bf0b4-9a87-437c-9208-a2725bf9fdd9" width=300 /> |
close #258
> #258 회원 탈퇴 기능 구현

- presentation/src/main/java/com/mashup/presentation/feature/guide/GuideScreen.kt
- presentation/src/main/res/values/strings.xml
- 가이드 UI 변경
- none
| 가이드 UI |![image](https://github.com/mash-up-kr/ssam-d-Android/assets/37477660/40a3590d-c576-47e1-aabe-96d9e5d1a553)|
close #269
> [feat] #269 가이드 UI 변경

- data/src/main/java/com/mashup/data/repository/CrashRepositoryImpl.kt
- data/src/main/java/com/mashup/data/source/remote/dto/responsebody/crash/CrashResponse.kt
- data/src/main/java/com/mashup/data/source/remote/service/ApiPattern.kt
- data/src/main/java/com/mashup/data/source/remote/service/CrashService.kt
- data/src/main/java/com/mashup/data/source/remote/source/datasource/RemoteCrashDataSource.kt
- domain/src/main/java/com/mashup/domain/model/Crash.kt
- domain/src/main/java/com/mashup/domain/repository/CrashRepository.kt
- domain/src/main/java/com/mashup/domain/usecase/crash/GetCrashDetailUseCase.kt
- domain/src/main/java/com/mashup/domain/usecase/crash/GetCrashesUseCase.kt
- domain/src/main/java/com/mashup/domain/usecase/crash/SendCrashReplyUseCase.kt
- 재성PR 연결 후 프리젠테이션 연결하겠습니다
- none
close #273
> 시그널존 api 데이터, 도메인 레이어 연결

- presentation/src/main/java/com/mashup/presentation/feature/chat/compose/ChatListScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/chat/model/RoomUiModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/chat/compose/Chat.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/chat/compose/ChatDetailScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/chat/model/ChatInfoUiModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/message/compose/MessageDetailScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/message/model/MessageDetailUiModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/home/ReceivedSignalContent.kt
- presentation/src/main/java/com/mashup/presentation/ui/common/KeyLinkChip.kt
- presentation/src/main/res/values/strings.xml
- 매칭키워드 개수로 시그널존 파악 후 후처리 
- 폰트크기 변경
- "#" 안붙어있던 키워드 수정
- none
| 채팅방리스트 |![KakaoTalk_Photo_2023-08-05-15-16-34 003](https://github.com/mash-up-kr/ssam-d-Android/assets/37477660/eb63a791-aaa0-4b82-8169-5ac9ad1483d7)|
| 채팅 |![KakaoTalk_Photo_2023-08-05-15-16-34 002](https://github.com/mash-up-kr/ssam-d-Android/assets/37477660/e0c95335-b55f-459e-99d8-09aada61cc21)|
| 메세지 |![KakaoTalk_Photo_2023-08-05-15-16-34 001](https://github.com/mash-up-kr/ssam-d-Android/assets/37477660/85b9f66c-5879-4ebc-bcd2-0d1955acfc04)|
close #270
> #270 채팅방 시그널존 ui 처리

- data/src/main/java/com/mashup/data/util/suspendRunCatching.kt
- domain/src/main/java/com/mashup/domain/exception/ConflictException.kt
- domain/src/main/java/com/mashup/domain/exception/KeyLinkException.kt
- domain/src/main/java/com/mashup/domain/usecase/login/CheckNicknameDuplicationUseCase.kt
- presentation/src/main/java/com/mashup/presentation/feature/login/LoginViewModel.kt
- #286 
- suspendRunCatching에서 errorbody 파싱하도록 수정
- 닉네임 수정에서 동작 확인 완료
close #286
> #286 suspendRunCatching 수정

- data/src/main/java/com/mashup/data/di/RepositoryModule.kt
- data/src/main/java/com/mashup/data/di/ServiceModule.kt
- data/src/main/java/com/mashup/data/source/remote/dto/responsebody/crash/CrashResponse.kt
- domain/src/main/java/com/mashup/domain/model/Crash.kt
- presentation/src/main/java/com/mashup/presentation/feature/chat/compose/ChatScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/chat/ChatDetailViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/chat/compose/ChatDetailScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/crash/CrashDetail.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/crash/CrashDetailViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/crash/CrashUiModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/message/compose/MessageDetailScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/guide/GuideScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/home/HomeScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/reply/chat/ChatReplyScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/reply/crash/CrashReplyScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/reply/crash/CrashReplyViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/signalzone/SignalZoneUiModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/signalzone/SignalZoneViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/signalzone/compose/CrashesContent.kt
- presentation/src/main/java/com/mashup/presentation/feature/signalzone/compose/SignalZoneScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/signalzone/navigation/SignalZoneNavigation.kt
- presentation/src/main/res/values/strings.xml
- 시그널존 presentaiton 서버 연결
- none
|크래시 화면 연결|https://github.com/mash-up-kr/ssam-d-Android/assets/37477660/10cb751b-2c78-46be-a466-505074c31376|
close #273
> 시그널존 presentaiton 서버 연결

- data/src/main/java/com/mashup/data/repository/SignalRepositoryImpl.kt
- domain/src/main/java/com/mashup/domain/repository/SignalRepository.kt
- domain/src/main/java/com/mashup/domain/usecase/SendSignalUseCase.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/message/navigation/MessageDetailNavigation.kt
- presentation/src/main/java/com/mashup/presentation/feature/signal/received/ReceivedSignalDetailRoute.kt
- presentation/src/main/java/com/mashup/presentation/feature/signal/send/SignalViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/signal/send/compose/SignalKeywordScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/signal/send/navigation/SignalNavigation.kt
- presentation/src/main/java/com/mashup/presentation/navigation/KeyLinkNavHost.kt
- presentation/src/main/res/values/strings.xml
- 시그널 보내기
- 시그널 디테일
- none
|시그널 보내기 | 시그널 디테일|
https://github.com/mash-up-kr/ssam-d-Android/assets/51108983/3f861696-1d32-4d48-8867-90c191e49610
https://github.com/mash-up-kr/ssam-d-Android/assets/51108983/e5f69d31-e48c-44c0-bce6-8ee342b4c7b4
close #<issue_number>
> #276 에러 스낵바

- data/src/main/java/com/mashup/data/repository/ChatRepositoryImpl.kt
- data/src/main/java/com/mashup/data/source/remote/source/datasource/RemoteChatDataSource.kt
- domain/src/main/java/com/mashup/domain/repository/ChatRepository.kt
- domain/src/main/java/com/mashup/domain/usecase/chat/GetChatInfoUseCase.kt
- domain/src/main/java/com/mashup/domain/usecase/chat/GetMessageDetailUseCase.kt
- presentation/src/main/java/com/mashup/presentation/feature/chat/navigation/ChatNavigation.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/chat/ChatDetailViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/chat/compose/ChatDetailScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/chat/compose/ChatInfoUiState.kt
- presentation/src/main/java/com/mashup/presentation/feature/detail/message/compose/MessageDetailScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/reply/ReplyContent.kt
- presentation/src/main/java/com/mashup/presentation/feature/reply/chat/ChatReplyScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/reply/crash/CrashReplyScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/reply/crash/CrashReplyViewModel.kt
- presentation/src/main/java/com/mashup/presentation/feature/reply/signal/ReceivedSignalReplyScreen.kt
- presentation/src/main/java/com/mashup/presentation/feature/reply/signal/ReceivedSignalReplyViewModel.kt
> #276 에러메시지 스낵바 표시
